/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ra52m
 */
public class Fill_Info extends javax.swing.JFrame {

    /**
     * Creates new form Fill_Info
     */
    public Fill_Info() {
        initComponents();
    }
    Main m = new Main();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JTextField();
        mobilenumber = new javax.swing.JTextField();
        devicetype = new javax.swing.JTextField();
        next = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 470, 220, 40));

        mobilenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenumberActionPerformed(evt);
            }
        });
        mobilenumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobilenumberKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobilenumberKeyTyped(evt);
            }
        });
        jPanel1.add(mobilenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 210, 40));
        jPanel1.add(devicetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 220, 40));

        next.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 870, 90, 50));

        buttonGroup2.add(jCheckBox1);
        jCheckBox1.setVerifyInputWhenFocusTarget(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 778, -1, -1));

        buttonGroup2.add(jCheckBox2);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 778, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/5.gif"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        String Username = name.getText().toString();
        String mobile = mobilenumber.getText().toString();
        String device = devicetype.getText().toString();
        if (name.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The name is mandatory");
        } else if (mobilenumber.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Mobile Number is mandatory");
        } else if (mobile.length() != 10) {
            JOptionPane.showMessageDialog(null, "The mobile Number Should be 10 Digits");
        } else if (devicetype.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "The Device type Number is mandatory");
        } else if (!jCheckBox1.isSelected() && !jCheckBox2.isSelected()) {
            JOptionPane.showMessageDialog(null, "You should select gender");
        } else {
            m.fillInformation(Username, mobile, device);
            if (jCheckBox1.isSelected()) {
                m.gender("Male");
            } else {
                m.gender("Female");
            }
            PlaceOrder p = new PlaceOrder();
            p.show();
        }

    }//GEN-LAST:event_nextActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void mobilenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenumberActionPerformed

    }//GEN-LAST:event_mobilenumberActionPerformed

    private void mobilenumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobilenumberKeyTyped

    }//GEN-LAST:event_mobilenumberKeyTyped

    private void mobilenumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobilenumberKeyPressed
        String phone = mobilenumber.getText();
        int length = phone.length();
        char c = evt.getKeyChar();
        // check for number 0 to 9
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            // check for length not more than 10 digits
            if (length < 10) {
                mobilenumber.setEditable(true);
            } else {
                mobilenumber.setEditable(false);
            }
        } else {
            // not allow for keys "back space" and "delete" for edit
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                // allow editable 
                mobilenumber.setEditable(true);
            } else {
                mobilenumber.setEditable(false);
                getToolkit().beep();
            }
        }

    }//GEN-LAST:event_mobilenumberKeyPressed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)) {
            name.setEditable(true);
        } else {
            name.setEditable(false);
        }
    }//GEN-LAST:event_nameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fill_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fill_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fill_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fill_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fill_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    public javax.swing.JTextField devicetype;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField mobilenumber;
    public static javax.swing.JTextField name;
    public javax.swing.JButton next;
    // End of variables declaration//GEN-END:variables
}
